"""add ml fields to vitals

Revision ID: 969a3dbf4c7e
Revises: 5723969d97ab
Create Date: 2026-06-10 09:50:25.603076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969a3dbf4c7e'
down_revision: Union[str, Sequence[str], None] = '5723969d97ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vitals', sa.Column('glucose', sa.Integer(), nullable=True))
    op.add_column('vitals', sa.Column('blood_pressure', sa.Integer(), nullable=True))
    op.add_column('vitals', sa.Column('bmi', sa.Integer(), nullable=True))
    op.add_column('vitals', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vitals', 'age')
    op.drop_column('vitals', 'bmi')
    op.drop_column('vitals', 'blood_pressure')
    op.drop_column('vitals', 'glucose')
    # ### end Alembic commands ###
